package COUNTRYcodes;

##########################################
#
# List of COUNTRY codes used to make institutions info
#
##########################################
%COUNTRY = (
'ac','not available',
'ad','andorra',
'ae','uae',
'af','not available',
'ag','not available',
'ai','not available',
'al','albania',
'am','armenia',
'an','nethantilles',
'ao','angola',
'aq','not available',
'ar','argentina',
'as','not available',
'at','austria',
'au','australia',
'aw','aruba',
'az','azerbaidjan',
'ba','bosnia',
'bb','barbados',
'bd','bangladesh',
'be','belgium',
'bf','burkina Faso',
'bg','bulgaria',
'bh','bahrain',
'bi','not available',
'bj','benin',
'bm','bermuda',
'bn','brunei',
'bo','bolivia',
'br','brazil',
'bs','not available',
'bt','not available',
'bv','not available',
'bw','botswana',
'by','belarus',
'bz','belize',
'ca','canada',
'cc','not available',
'cd','not available',
'cf','centralafrica Rep.',
'cg','not available',
'ch','switzerland',
'ci','ivory Coast',
'ck','not available',
'cl','chile',
'cm','not available',
'cn','china',
'co','colombia',
'com','usa',
'cr','costa Rica',
'cu','cuba',
'cv','not available',
'cx','not available',
'cy','cyprus',
'cz','czech',
'de','germany',
'dj','djibouti',
'dk','denmark',
'dm','not available',
'do','dominican Rep.',
'dz','algeria',
'ec','ecuador',
'edu','usa',
'ee','estonia',
'eg','egypt',
'eh','not available',
'er','not available',
'es','spain',
'et','ethiopia',
'fi','finland',
'fj','fiji',
'fk','not available',
'fm','not available',
'fo','faroes',
'fr','france',
'ga','gabon',
'gd','not available',
'ge','georgia',
'gf','not available',
'gg','guernsey',
'gh','ghana',
'gi','gibraltar',
'gl','greenland',
'gm','not available',
'gn','not available',
'gov','usa',
'gp','guadeloupe',
'gq','not available',
'gr','greece',
'gs','not available',
'gt','guatemala',
'gu','guam',
'gw','not available',
'gy','guyana',
'hk','hong Kong',
'hm','not available',
'hn','honduras',
'hr','croatia',
'ht','haiti',
'hu','hungary',
'id','indonesia',
'ie','ireland',
'il','israel',
'im','man',
'in','india',
'int','intorg',
'io','not available',
'iq','not available',
'ir','iran',
'is','iceland',
'it','italy',
'je','jersey',
'jm','jamaica',
'jo','jordan',
'jp','japan',
'ke','kenya',
'kg','kyrgystan',
'kh','cambodia',
'ki','not available',
'km','not available',
'kn','kitts',
'kp','not available',
'kr','southkorea',
'kw','kuwait',
'ky','not available',
'kz','kazakhstan',
'la','laos',
'lb','lebanon',
'lc','stlucia',
'li','liechtenstein',
'lk','srilanka',
'lr','liberia',
'ls','lesotho',
'lt','lithuania',
'lu','luxembourg',
'lv','latvia',
'ly','libya',
'ma','morocco',
'mc','not available',
'md','moldova',
'mg','madagascar',
'mh','marshall',
'mil','usa',
'mk','macedonia',
'ml','mali',
'mm','not available',
'mn','mongolia',
'mo','macao',
'mp','not available',
'mq','martinique',
'mr','not available',
'ms','montserrat',
'mt','malta',
'mu','mauritius',
'mv','maldives',
'mw','malawi',
'mx','mexico',
'my','malaysia',
'mz','mozambique',
'na','namibia',
'nc','newcaledonia',
'ne','niger',
'net','usa',
'nf','not available',
'ng','not available',
'ni','nicaragua',
'nl','netherlands',
'no','norway',
'np','nepal',
'nr','not available',
'nu','not available',
'nz','newzealand',
'om','oman',
'org','assocs',
'ea','assocs',
'pa','panama',
'pe','peru',
'pf','not available',
'pg','papua',
'ph','philippines',
'pk','pakistan',
'pl','poland',
'pm','not available',
'pn','not available',
'pr','puerto Rico',
'pt','portugal',
'pw','not available',
'py','paraguay',
'qa','qatar',
're','reunion',
'ro','romania',
'ru','russia',
'rw','not available',
'sa','saudi Arabia',
'sb','solomon',
'sc','seychelles',
'sd','sudan',
'se','sweden',
'sg','singapore',
'sh','not available',
'si','slovenia',
'sj','not available',
'sk','slovakia',
'sl','not available',
'sm','sanmarino',
'sn','senegal',
'so','not available',
'st','not available',
'su','russia',
'sv','salvador',
'sy','not available',
'sz','swaziland',
'tc','not available',
'td','not available',
'tf','not available',
'tg','togo',
'th','thailand',
'tj','not available',
'tk','not available',
'tm','not available',
'tn','tunisia',
'to','not available',
'tp','not available',
'tr','turkey',
'tt','trinidad',
'tv','not available',
'tw','taiwan',
'tz','tanzania',
'ua','ukraine',
'ug','uganda',
'uk','UK',
'um','not available',
'us','usa',
'uy','uruguay',
'uz','uzbekistan',
'va','vatican',
'vc','not available',
've','venezuela',
'vg','britvirgin',
'vi','not available',
'vn','vietnam',
'vu','vanuatu',
'wf','not available',
'ws','samoa',
'ye','yemen',
'yt','not available',
'yu','yugoslavia',
'za','southafrica',
'zm','zambia'
		 );

@africa = (
	     'algeria','angola','benin','botswana','burkina Faso',
	     'centralafrica Rep.','djibouti','egypt','ethiopia',
	     'gabon','ghana','ivory Coast','kenya','lesotho','liberia',
	     'libya','madagascar','malawi','mali','mauritius','morocco',
	     'mozambique','namibia','niger','r&eacute;union','senegal',
	     'southafrica','sudan','swaziland','tanzania','togo','tunisia',
	     'uganda','zambia');

@america = (
	    'argentina','aruba','barbados','belize','bermuda','bolivia',
	    'brazil','brit. Virgin Isl.','canada','chile','colombia',
	    'costa Rica','cuba','dominican Rep.','ecuador','salvador',
	    'greenland','guadeloupe','guatemala','guyana','ha&iuml;ti',
	    'honduras','jamaica','martinique','mexico','montserrat',
	    'nicaragua','panama','paraguay','peru',
	    'puerto Rico','kitts &amp; Nevis','st Lucia',
	    'trinidad &amp; Tobago','USA','uruguay','venezuela');

@asia = (
	 'armenia','azerbaidjan','bahrain','bangladesh','brunei','cambodia',
	 'china','georgia','hong Kong','india','indonesia','iran','israel',
	 'japan','jordan','kazakhstan','kuwait','kyrgystan','laos','lebanon',
	 'macao','malaysia','maldives','mongolia','nepal','oman','pakistan',
	 'palestinian Authority','philippines','qatar','saudi Arabia',
	 'seychelles','singapore','southkorea','sri Lanka','taiwan',
	 'thailand','turkey','united Arab Emirates','uzbekistan','vietnam',
	 'yemen');


@europe = ('albania','andorra','austria','belarus','belgium',
	   'bosnia and Herzegovina','bulgaria','cyprus','czech Republic',
	   'denmark','estonia','faroes','finland','france','germany',
	   'gibraltar','greece','guernsey','hungary','iceland','ireland',
	   'italy','jersey','latvia','liechtenstein','lithuania',
	   'luxembourg','macedonia (FYROM)','malta','man','moldova',
	   'netherlands','norway','poland','portugal','romania','russia',
	   'san Marino','slovakia','slovenia','spain','sweden','switzerland',
	   'turk. Rep. of Northern Cyprus','ukraine','UK',
	   'vatican','yugoslavia');



@oceania = ('australia','fiji','guam','marshall Islands',
	   'new Caledonia','new Zealand','papua New Guinea','samoa',
	   'solomon Islands','vanuatu');

1;

